POST  http://localhost:5000/register 
Content-Type: application/json

{
    "email":"w@w.com",
    "first_name":"jicksaw",
    "last_name":"killer",
    "password":"12345678"
}

###

POST  http://localhost:5000/login
Content-Type: application/json

{
    "email":"w@w.com",
    "password":"12345678"
}

###
GET http://localhost:5000/auth/facebook


###
GET http://localhost:5000/auth/facebook/callback
